name: Tox

on: pull_request

jobs:
  build:
    # Configure to use all os'es.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        # exclude windows for now.
        os: [ubuntu-latest, macos-latest]
    env:
      ON_GH: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tox
        run: |
          tox -v
